### PR TITLE
Issue #182 add namespace support to `DataCube.process` and related

### LINKED ISSUE #182: Add namespace support
add namespace support in `Datacube.process` (and related) so that process graphs can be built using process from other namespaces than the default ("backend")

### PR DESCRIPTION
**Pull request by soxofaan**
fixes #182: adds namespace support to `DataCube.process`, `PGNode`, `ProcessGraphVisitor`, `GraphFlattener`

This improvements changes the `ProcessGraphVisitor` API changed a bit by adding `namespace` argument to `enterProcess` and `leaveProcess` (which will break openeo-python-driver and openeo-geopyspark-driver) 
Before pushing this, I wanted to go through PR+review first

(I bumped version to 0.5.0a1 to clearly mark API change)

### CODE REVIEW

**Comment by soxofaan** [comment]
related PRs for python and geopyspark driver:
- https://github.com/Open-EO/openeo-python-driver/pull/61
- https://github.com/Open-EO/openeo-geopyspark-driver/pull/67

**Comment by soxofaan** [comment]
@jdries   can you have a quick look if it's ok to merge these PRs?

**Comment by jdries** [comment]
Reviewed, the most critical question to me is whether 'namespace' is accepted by openEO partners as a new word in our terminology? We have been using it, but not sure if it was generally presented in the PSC.
@m-mohr  Do you happen to know?
Of course, it's not like I immediately have an alternative available.

**Comment by soxofaan** [comment]
"namespace" as a concept and field is already part of the API, e.g. https://openeo.org/documentation/1.0/developers/api/reference.html#section/Processes/Process-Graphs 

it was introduced here: https://github.com/Open-EO/openeo-api/issues/305

**Comment by m-mohr** [comment]
Yes, that seems all fine.

**Comment by soxofaan** [comment]
> We don't have agreed on Open-EO/openeo-api#348 yet though.

indeed, but that is not a blocker for this issue #183: 
it just introduces function arguments to allow setting the (optional) `namespace` field in process nodes (following the existing 1.0.0 spec)

**Comment by soxofaan** [comment]
thanks!

**Pull request merged**
