### PR TITLE
EP-3521 propose 2 new ways of specifying callbacks

### PR DESCRIPTION
**Pull request by jdries**
This PR is about how we specify callbacks in the Python client. Untill now, we had:

- support for specific cases, like band math
- direct calls for process + callback, like reduce_temporal_udf, apply_dimension
- some use of internal API (PGNode) where users required some knowledge of openeo process specs

So basically not a generic solution that works in all cases.
This PR adds a processbuilder, which is similar to an ImageCollection/DataCube so you build a process graph by calling methods on it.
The difficult bit is how to link the result into the parent graph, with as little hassle as possible. This is context specific, as different processes use different parameter names etcetera.

Both of these solutions have been implemented, question is which one we prefer and want to push in our docs.

Solution 1: use a python function to define a callback (so yes, a real callback):

```
    collection = con100.load_collection("S2")

    def callback(data:ProcessBuilder):
        return data.absolute().run_udf(code='myfancycode', runtime='Python')

    neighbors = collection.apply_neighborhood(process=callback, size=[
        {'dimension': 'x', 'value': 128, 'unit': 'px'},
        {'dimension': 'y', 'value': 128, 'unit': 'px'}
    ], overlap=[
        {'dimension': 't', 'value': 'P10d'},
    ])
```

Solution 2: a builder pattern:
```
    callback = collection.apply_neighborhood( size=[
        {'dimension': 'x', 'value': 128, 'unit': 'px'},
        {'dimension': 'y', 'value': 128, 'unit': 'px'}
    ], overlap=[
        {'dimension': 't', 'value': 'P10d'},
    ])
    neighbors = callback.absolute().run_udf(code='myfancycode',runtime='Python').done()

```

So which solution is best?
- (1) maximally uses python language to specify an actual callback
- (2) uses a builder pattern, which could be well known among programmers, but not seen so often in Python API's
- my feeling is that (1) is a bit closer to the openEO API, so perhaps makes most sense?

### CODE REVIEW

**Comment by jdries** [comment]
Solution number 1 gets even better when you add lambda's. It allows us to write code like this:

`bandsum = collection.apply(process=lambda data:array_element(data,index=1) + array_element(data,index=2))`

This is very close to how openEO processes are defined and work, but also quite 'Pythonic' if you ask me.

**Comment by jdries** [comment]
Just noticed that both the Javascript and R clients have a solution similar to number 1. That makes it an easy call, will merge.
In followup work, we'll need to add functions for all processes, possibly generating them.

**Comment by bgoesswe** [comment]
Just to note: I m not sure if this still works, but some time ago I created a generation tool for the processes in 
https://github.com/Open-EO/openeo-python-client/pull/112

**Comment by bgoesswe** [comment]
More specifically : https://github.com/Open-EO/openeo-python-client/blob/process_generation/openeo/internal/processes_gen.py

**Pull request merged**
