### PR TITLE
band name aliases

### PR DESCRIPTION
**Pull request by jdries**

### CODE REVIEW

**Comment by jdries** [comment]
In this proposal, which indeed seems better, would users of the old band names get an error? (Because they try to use a band name that is not in the metadata?)

**Comment by soxofaan** [comment]
Ah ok, so it is actually also about client side resolving of band names.
So it is intentional to depend on a non-standard metadata field "internal_name"?
(because of the "internal" I assumed it was something internally for geopyspark driver).

**Comment by jdries** [comment]
@soxofaan  Ok to merge? Seems fine for me, and I need the aliases in the backend.

**Comment by soxofaan** [comment]
yes look a lot better and more generic now

might need some test coverage though (not necessarily merge blocker)

**Comment by jdries** [comment]
Ok, will merge already!

**Pull request merged**
