### PR TITLE
request for information

### PR DESCRIPTION
**Pull request by Pratichhya**
not clear regarding the visualization

### CODE REVIEW

**Comment by soxofaan** [comment]
can you share the plots you reproduced?

**Comment by Pratichhya** [comment]
This is my **evi-composite.tiff**  when I plot based on whatever output is received.
image
and this is masked_evi-composite.tiff
image

**Comment by soxofaan** [comment]
for that first (unmasked) plot, I indeed probably added something like `vmin=0, vmax=1` to the plot to limit the visualization to the valid/interesting part of the evi range.
Can you try to add that

**Comment by Pratichhya** [comment]
Yes, it is due to range selected for visualization but I don't think it is vmax=1 and vmin =0. It gives me different output than that in the guide even when I select in the range of -1 to 1. But may be if would be helpful is a note is provided. 
image
 
# image in the guide
image

**Comment by soxofaan** [comment]
apparently the original evi-composite image is indeed out of sync with what you currently get from executing the related code

I've updated the inage in 03fdfcb

**Comment by soxofaan** [comment]
@Pratichhya   FYI: for these kind of questions/requests, you should not create a pull request, but just create a basic issue from https://github.com/Open-EO/openeo-python-client/issues

**Pull request closed without merging**
